### ISSUE TITLE
memory leak with v0.3.2 

### ISSUE THREAD

**Issue by medic123de** [gtkforphp/cairo#13] opened 2015-02-05 11:37 UTC
Hi,
using php-fpm there seems to be a memory leak regarding FtFontFace

<?php
$fontFile = "arial.ttf";

$surface = new \CairoImageSurface(
    CairoFormat::ARGB32,
    750,
    750
);

$context = new \CairoContext( $surface );
$fontFaceObject = new \CairoFtFontFace($fontFile);

// commenting next line will not leak
$context->setFontFace( $fontFaceObject );
?>

I found  n-times the content of arial.ttf within allocated memory, where n equals number of requests.

therefore, the memory leak is directly related to sizeof($fontFaceObject)   :-(

**Comment by swen100** [comment] 2015-02-05 12:31
i think that the memory-leaks (see also #2) were introduced with version 0.3.x and obviously seem to be caused by the (freetype-)font-handling.

I hope, that Elisabeth or one of the other developers with high c# skills have some time to take a deeper look at this problem.

**Comment by medic123de** [comment] 2015-02-05 19:00
https://github.com/gtkforphp/cairo/pull/15  works for me.

**Comment by auroraeosrose** [comment] 2015-06-24 23:24
this should be fixed now

**Closed by auroraeosrose** 2015-06-24 23:24 UTC
